config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to =>"homes#top"
  devise_for :users
  get "home/about"=>"homes#about"
  get "search" => "searches#search"
  get "tag_search" => "tag_searches#tag_search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
   get 'relationships/followers' => 'relationships#followers', as: 'followers'
   get 'relationships/followings' => 'relationships#followings', as: 'followings'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  validates :tag,presence:true

  scope :latest, -> {order(created_at: :desc)}
  scope :rate_count, -> {order(rate: :desc)}

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
before_action :correct_user, only: [:edit, :update]

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
    @book_comment = BookComment.new
    @book_comments = BookComment.all
  end

  def index
    if params[:latest]
      @books = Book.latest
    elsif params[:rate_count]
      @books = Book.rate_count
    else
      @books = Book.all
    end
      @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :rate, :tag)
  end

  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>

  <div class="form-group">
    <%= f.label :Tag %>
    <%= f.text_field :tag, class: 'form-control book_tag' %>
  </div>

  <% if book.id === nil %>
    <div class="form-group" id="star">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star, class:'form-control' %>
    </div>

    <div id="post_raty"></div>
    <script>
      $(document).on('turbolinks:load', function() {
      let raty_elem = document.querySelector('#post_raty');
      raty_elem.innerHTML = ""
      let option = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'book[rate]',
        };
      raty(raty_elem,option);
     });
    </script>

  <% else %>
    <%= render "static_rate", book: book %>
  <% end %>

  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Tag</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book %></td>
        <td><%= book.body %></td>
        <td><%= link_to book.tag, tag_search_path(word: book.tag) %></td>
        <th id="favorite_btn_<%= book.id %>">
         <%= render 'favorites/favorite', book: book %>
        </th>
        <th>
        コメント件数：<%= book.book_comments.count %>
        </th>
        <td><%= render "books/static_rate", book: book %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/_static_rate.html.erb
<div id="rate_<%= book.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
    let raty_<%= book.id %> = document.querySelector('#rate_<%= book.id %>');
    rate_<%= book.id %>.innerHTML = ""
    let option_<%= book.id %> = {
        starOn: "<%= asset_path('star-on.png') %>",
        starOff: "<%= asset_path('star-off.png') %>",
        starHalf: "<%= asset_path('star-half.png') %>",
        score: "<%= book.rate %>",
        readOnly: true,
      };
    raty(raty_<%= book.id %> ,option_<%= book.id %>);
});
</script>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', @book %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
       <%= render 'layouts/errors', obj: @book %>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', books_path(latest: "true") %>
      |<%= link_to '評価の高い順', books_path(rate_count: "true") %>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book, book: @book_new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= link_to @book.tag, tag_search_path(word: @book.tag) %></td>
          <th id="favorite_btn_<%= @book.id %>">
            <%= render 'favorites/favorite', book: @book %>
          </th>
          <th>
            コメント件数：<%= @book.book_comments.count %>
          </th>
          <td><%= render "static_rate", book: @book %></td>
          <td>
            <% if @book.user == current_user %>
            <%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
          <td>
            <% if @book.user == current_user %>
            <%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%>              <% end %>
          </td>
        </tr>
      </table>

      <table>
        <tbody id=comment_list>
            <%= render "book_comments/comment_list", book: @book %>
        </tbody>
      </table>

      <div>
        <%= form_with model: [@book, @book_comment], data: {remote: true} do |f| %>
        <%= f.text_area :comment, rows: '5', class: 'form-control book_comment' %>
        <%= f.submit "送信" %>
       <% end %>
      </div>
    </div>
  </div>
</div>